
// filename: cap_robotCleanerMovement.als
module cap_robotCleanerMovement
open IoTBottomUp
one sig cap_robotCleanerMovement extends Capability {}
{
    attributes = cap_robotCleanerMovement_attr
}
abstract sig cap_robotCleanerMovement_attr extends Attribute {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement extends cap_robotCleanerMovement_attr {}
{
    values = cap_robotCleanerMovement_attr_robotCleanerMovement_val
} 
abstract sig cap_robotCleanerMovement_attr_robotCleanerMovement_val extends AttrValue {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_homing extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_idle extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_charging extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_alarm extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_powerOff extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_reserve extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_point extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_after extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
one sig cap_robotCleanerMovement_attr_robotCleanerMovement_val_cleaning extends cap_robotCleanerMovement_attr_robotCleanerMovement_val {}
