
// filename: cap_robotCleanerCleaningMode.als
module cap_robotCleanerCleaningMode
open IoTBottomUp
one sig cap_robotCleanerCleaningMode extends Capability {}
{
    attributes = cap_robotCleanerCleaningMode_attr
}
abstract sig cap_robotCleanerCleaningMode_attr extends Attribute {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode extends cap_robotCleanerCleaningMode_attr {}
{
    values = cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val
} 
abstract sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val extends AttrValue {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_auto extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_part extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_repeat extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_manual extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_stop extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
one sig cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val_map extends cap_robotCleanerCleaningMode_attr_robotCleanerCleaningMode_val {}
